import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" + Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_common_java8: String = "androidx.lifecycle:lifecycle-common-java8:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val lifecycle_viewmodel_ktx: String = "androidx.lifecycle:lifecycle-viewmodel-ktx:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_viewmodel_savedstate: String =
            "androidx.lifecycle:lifecycle-viewmodel-savedstate:" + Versions.androidx_lifecycle

    /**
     * https://github.com/lisawray/groupie
     */
    const val groupie: String = "com.xwray:groupie:" + Versions.com_xwray

    /**
     * https://github.com/lisawray/groupie
     */
    const val groupie_kotlin_android_extensions: String =
            "com.xwray:groupie-kotlin-android-extensions:" + Versions.com_xwray

    /**
     * https://github.com/grpc/grpc-java
     */
    const val grpc_netty: String = "io.grpc:grpc-netty:" + Versions.io_grpc

    /**
     * https://github.com/grpc/grpc-java
     */
    const val grpc_okhttp: String = "io.grpc:grpc-okhttp:" + Versions.io_grpc

    /**
     * https://github.com/grpc/grpc-java
     */
    const val grpc_protobuf: String = "io.grpc:grpc-protobuf:" + Versions.io_grpc

    /**
     * https://github.com/grpc/grpc-java
     */
    const val grpc_stub: String = "io.grpc:grpc-stub:" + Versions.io_grpc

    const val com_google_android_play_core_ktx: String = "com.google.android.play:core-ktx:" +
            Versions.com_google_android_play_core_ktx

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val androidx_core_core_ktx: String = "androidx.core:core-ktx:" +
            Versions.androidx_core_core_ktx

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/florent37/InlineActivityResult
     */
    const val inline_activity_result_kotlin: String =
            "com.github.florent37:inline-activity-result-kotlin:" +
            Versions.inline_activity_result_kotlin

    /**
     * http://developers.google.com/photos
     */
    const val google_photos_library_client: String =
            "com.google.photos.library:google-photos-library-client:" +
            Versions.google_photos_library_client

    const val firebase_crashlytics_gradle: String =
            "com.google.firebase:firebase-crashlytics-gradle:" +
            Versions.firebase_crashlytics_gradle

    const val firebase_crashlytics: String = "com.google.firebase:firebase-crashlytics:" +
            Versions.firebase_crashlytics

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
            Versions.leakcanary_android

    const val play_services_auth: String = "com.google.android.gms:play-services-auth:" +
            Versions.play_services_auth

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val activity_ktx: String = "androidx.activity:activity-ktx:" + Versions.activity_ktx

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    const val viewbinding: String = "androidx.databinding:viewbinding:" + Versions.viewbinding

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * https://github.com/square/retrofit/
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.retrofit

    /**
     * https://github.com/ajalt/timberkt
     */
    const val timberkt: String = "com.github.ajalt:timberkt:" + Versions.timberkt

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://github.com/coil-kt/coil
     */
    const val coil: String = "io.coil-kt:coil:" + Versions.coil
}
