import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.5"
             // available: "1.3.5-1.4-M1-release-99"

    const val com_github_lisawray_groupie: String = "2.8.0"

    const val org_jetbrains_kotlin: String = "1.3.71"

    const val androidx_navigation: String = "2.2.1"

    const val androidx_lifecycle: String = "2.2.0"

    const val com_squareup_moshi: String = "1.9.2"

    const val androidx_room: String = "2.2.5"

    const val io_grpc: String = "1.28.0" // available: "1.28.1"

    const val com_google_android_play_core_ktx: String = "1.7.0"

    const val com_android_tools_build_gradle: String = "3.6.1" // available: "3.6.2"

    const val androidx_core_core_ktx: String = "1.2.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val inline_activity_result_kotlin: String = "1.0.3"

    const val google_photos_library_client: String = "1.4.0" // available: "1.5.0"

    const val firebase_crashlytics_gradle: String = "2.0.0-beta02"

    const val drag_select_recyclerview: String = "2.4.0"

    const val firebase_functions_ktx: String = "19.0.2"

    const val firebase_crashlytics: String = "17.0.0-beta01"

    const val firebase_config_ktx: String = "19.1.3"

    const val firebase_analytics: String = "17.2.3" // available: "17.3.0"

    const val play_services_auth: String = "17.0.0" // available: "18.0.0"

    const val constraintlayout: String = "1.1.3"

    const val google_services: String = "4.3.3"

    const val activity_ktx: String = "1.1.0"

    const val fragment_ktx: String = "1.2.3" // available: "1.2.4"

    const val recyclerview: String = "1.1.0"

    const val lint_gradle: String = "26.6.1" // available: "26.6.2"

    const val viewbinding: String = "3.6.1" // available: "3.6.2"

    const val appcompat: String = "1.1.0"

    const val joda_time: String = "2.10.5"

    const val koda_time: String = "2.0.0"

    const val material: String = "1.1.0"

    const val retrofit: String = "2.8.0" // available: "2.8.1"

    const val timberkt: String = "1.5.1"

    const val kotpref: String = "2.10.0"

    const val vector: String = "0.6.0" // available: "0.6.1"

    const val aapt2: String = "3.6.1-6040484" // available: "3.6.2-6040484"

    const val coil: String = "0.9.5"

    /**
     * Current version: "6.2.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.3"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
