import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.3"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val androidx_navigation: String = "2.2.1"

    const val androidx_lifecycle: String = "2.2.0"

    const val com_xwray: String = "2.7.2"

    const val com_google_android_play_core_ktx: String = "1.6.5"

    const val com_android_tools_build_gradle: String = "3.6.0"

    const val androidx_core_core_ktx: String = "1.2.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val inline_activity_result_kotlin: String = "1.0.3"

    const val google_photos_library_client: String = "1.4.0"

    const val firebase_crashlytics_gradle: String = "2.0.0-beta02"

    const val firebase_crashlytics: String = "17.0.0-beta01"

    const val leakcanary_android: String = "2.2"

    const val play_services_auth: String = "17.0.0"

    const val constraintlayout: String = "1.1.3"

    const val google_services: String = "4.3.3"

    const val activity_ktx: String = "1.1.0"

    const val fragment_ktx: String = "1.2.2"

    const val recyclerview: String = "1.1.0"

    const val lint_gradle: String = "26.6.0"

    const val viewbinding: String = "3.6.0"

    const val appcompat: String = "1.1.0"

    const val material: String = "1.1.0"

    const val timberkt: String = "1.5.1"

    const val aapt2: String = "3.6.0-6040484"

    const val coil: String = "0.9.5"

    /**
     * Current version: "5.6.4"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.2.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
